from app.admin.models import *
from app.users.models import *
from app.roles.models import *
from app.positions.models import *
from app.departments.models import *
from app.emails.models import *
from app.predicts.models import *
from app.ratings.models import *
from app.subdivisions.models import *
from app.groups.models import *
from app.stimuls.models import *