"""add stimul model

Revision ID: 01e280ef5df9
Revises: 9ef7a1dee942
Create Date: 2023-12-22 14:36:39.846264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e280ef5df9'
down_revision: Union[str, None] = '9ef7a1dee942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stimuls',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('q1', sa.String(), nullable=True),
    sa.Column('q2', sa.String(), nullable=True),
    sa.Column('q3', sa.String(), nullable=True),
    sa.Column('q4', sa.String(), nullable=True),
    sa.Column('q5', sa.String(), nullable=True),
    sa.Column('q6', sa.String(), nullable=True),
    sa.Column('q7', sa.String(), nullable=True),
    sa.Column('q8', sa.String(), nullable=True),
    sa.Column('q9', sa.String(), nullable=True),
    sa.Column('q10', sa.String(), nullable=True),
    sa.Column('q11', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stimuls')
    # ### end Alembic commands ###
