"""add group  model

Revision ID: 9ef7a1dee942
Revises: eb5d7c8dd2b4
Create Date: 2023-12-22 08:59:20.930685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef7a1dee942'
down_revision: Union[str, None] = 'eb5d7c8dd2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group')
    )

    op.add_column('user_bots', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_bots', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_bots', type_='foreignkey')
    op.drop_constraint(None, 'user_bots', type_='foreignkey')
    op.alter_column('user_bots', 'group',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user_bots', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('user_bots', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('user_bots', 'group_id')
    op.drop_constraint(None, 'subdivision_bots', type_='foreignkey')
    op.alter_column('subdivision_bots', 'link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subdivision_bots', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('subdivision_bots', 'subdivision_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('subdivision_bots', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'department_bots', type_='foreignkey')
    op.alter_column('department_bots', 'link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('department_bots', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('department_bots', 'department_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('department_bots', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_table('groups')
    # ### end Alembic commands ###
